  name: nono
  description: "A new Flutter project."

  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: ^3.7.2

  dependencies:
    flutter:
      sdk: flutter
    url_launcher: ^6.1.14
    shared_preferences: ^2.2.2
    smooth_page_indicator: ^1.1.0
    lottie: ^3.3.1

    # ğŸ”¹ ì•„ì´ì½˜ íŒ¨í‚¤ì§€
    cupertino_icons: ^1.0.8

    # ğŸ”¹ Firebase ê´€ë ¨ íŒ¨í‚¤ì§€ ì¶”ê°€
    firebase_core: ^3.12.1   # Firebase ì´ˆê¸°í™”
    firebase_auth: ^5.5.1    # Firebase ì¸ì¦
    firebase_storage: ^12.4.4 # Firebase ìŠ¤í† ë¦¬ì§€ (ì´ë¯¸ì§€ ì—…ë¡œë“œ)
    cloud_firestore: ^5.0.0 # Firestore (ê²Œì‹œê¸€ ì €ì¥)

    # ğŸ”¹ ì¹´ë©”ë¼ & ê°¤ëŸ¬ë¦¬ì—ì„œ ì´ë¯¸ì§€ ì„ íƒ
    image_picker: ^1.0.7


    # ğŸ”¹ ì•ˆë“œë¡œì´ë“œ ê¶Œí•œ ìš”ì²­ (API 33+ ëŒ€ì‘)
    permission_handler: ^11.0.1
    file_picker: ^9.0.0

    # ğŸ”¹ ë„¤ì´í‹°ë¸Œ ìŠ¤í”Œë˜ì‹œ í™”ë©´ ì„¤ì •
    flutter_native_splash: ^2.4.5

    noise_meter: ^5.0.2
    flutter_sound: ^9.2.13+1
    record: ^6.0.0
    path_provider: ^2.0.15
    fl_chart: ^0.66.0

  dev_dependencies:
    flutter_test:
      sdk: flutter

    # ğŸ”¹ Linting ê·œì¹™ (flutter_lints ìµœì‹  ë²„ì „ ì‚¬ìš© ì‹œ flutter_native_splash ì˜¤ë¥˜ ë°œìƒ ê°€ëŠ¥)
    flutter_lints: ^2.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/logo.png
      - assets/thumbs_up.png
      - assets/close.png
      - assets/camera.png
      - assets/Image.png
      - assets/onboarding1.png
      - assets/onboarding2.png
      - assets/onboarding3.png
      - assets/products/ë‘êº¼ìš´ ì»¤íŠ¼.jpeg
      - assets/products/ë°©ìŒ ë¬¸í‹ˆ í…Œì´í”„.jpeg
      - assets/products/ë°©ìŒí¼.jpeg
      - assets/products/ì†ŒìŒì°¨ë‹¨ì´ì–´í°.jpeg
      - assets/products/ì´ì–´í”ŒëŸ¬ê·¸.jpeg
      - assets/products/ì¸µê°„ì†ŒìŒ ë§¤íŠ¸.jpeg
      - assets/lawyers/ê³½ë‘íŒ”.png
      - assets/lawyers/ê¹€ë„ìœ¤.png
      - assets/lawyers/ê¹€ë¯¼ì§€.png
      - assets/lawyers/ì†¡ìœ¤ì„­.png
      - assets/market.png
      - assets/call.png
      - assets/gov.png
      - assets/police.png
      - assets/tutorial_1_1.png
      - assets/tutorial_1_2.png
      - assets/tutorial_2.png
      - assets/tutorial_3.png
      - assets/consultation.png
      - assets/form_icon.png
      - assets/noise_meter.png
      - assets/call_consult.png
      - assets/web_consult.png
      - assets/message.png
      - assets/phone.png
      - assets/warning_icon.png
      - assets/big_police.png
      - assets/loading_animation.json
    fonts:
      - family: Pretendard
        fonts:
          - asset: assets/fonts/Pretendard-Regular.ttf
          - asset: assets/fonts/Pretendard-Bold.ttf
            weight: 700
          - asset: assets/fonts/Pretendard-Medium.ttf
            weight: 500
          - asset: assets/fonts/Pretendard-Light.ttf
            weight: 300
          - asset: assets/fonts/Pretendard-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Pretendard-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Pretendard-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Pretendard-Thin.ttf
            weight: 100

  flutter_native_splash:
    color: "#000000"
    image: assets/logo.png
    android: true
    ios: true
    fullscreen: true
